name: Build

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Seoul"
          timezoneMacos: "Asia/Seoul"
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      - name: install yarn
        run: |
          npm install -g yarn

      - name: prepare dependency
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn install
          
      - name: build project
        run: |
          yarn build
          mkdir -p build
          date > build/generated.txt
      - name: upload project
        run: |
          git config user.name qlqhqo2341
          git config user.email qlqhqo2341@naver.com
          git checkout -b build
          git add -f build
          git commit -m "Finish Build on actions-$GITHUB_RUN_NUMBER"
          git push -f --set-upstream origin build
