# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ build ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: actions/set-timezone-action@v1.1
        with:
          timezoneLinux: "Asia/Seoul"
          timezoneMacos: "Asia/Seoul"
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
        
      - name: install yarn
        run: |
          npm install -g yarn
          
      - name: build project
        run: |
          yarn install
          yarn build
          date > build/generated.txt
      - name: upload project
        run: |
          git config user.name qlqhqo2341
          git config user.email qlqhqo2341@naver.com
          git fetch origin
          git checkout --track origin/build
          git add -f build
          git commit -m "Finish Build on actions-$GITHUB_RUN_NUMBER"
          git push -f
