name: Build

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Seoul"
          timezoneMacos: "Asia/Seoul"
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
        
      - name: install yarn
        run: |
          npm install -g yarn
          
      - name: build project
        run: |
          yarn install
          # yarn build
          date > build/generated.txt
      - name: upload project
        run: |
          git config user.name qlqhqo2341
          git config user.email qlqhqo2341@naver.com
          git branch -b build
          git add -f build
          git commit -m "Finish Build on actions-$GITHUB_RUN_NUMBER"
          git push -f --set-upstream origin build
